# Generated by Django 4.2.3 on 2023-08-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionlisting_currentprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='currentPrice',
            field=models.IntegerField(),
        ),
    ]
